apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-deployment.fullname" . }}
  argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "test-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test-deployment.selectorLabels" . | nindent 4 }}
